dist: xenial

language: python

matrix:
  include:
    - python: 3.7

before_install:

  - wget https://repo.anaconda.com/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda

install:

  - conda env create hmc-tomography
  - pip install -e . --force-reinstall
  - conda activate hmc-tomography
  - pip install -e . --force-reinstall

script:
  - cd bin
  - which python
  - python3 ../hmc_tomography/tests/test_all.py
  - conda deactivate
  - which python
  - python3 ../hmc_tomography/tests/test_all.py
