language: python

matrix:
  include:
    - name: "Python 3.6.5 on macOS (xcode9.4)"
      os: osx
      env: BADGE=osx36
      osx_image: xcode9.4
      language: shell
      before_install:
        - python --version
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov
    - name: "Python 3.7.3 on macOS (xcode10.2)"
      os: osx
      env: BADGE=osx37
      osx_image: xcode10.2
      language: shell
      before_install:
        - python --version
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov
    - name: "Python 3.6 on Linux"
      os: linux
      env: BADGE=linux36
      language: python
      python: 3.6
    - name: "Python 3.7 on Linux"
      os: linux
      env: BADGE=linux37
      language: python
      python: 3.7
    - name: "Python 3.6.8 on Windows"
      os: windows
      env: BADGE=windows36
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.4 on Windows"
      os: windows
      env: BADGE=windows37
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip install -e .

script:
  - which python3
  - which python
  - python3 --version
  - python --version
  - if ["$TRAVIS_OS_NAME" == "windows"]; then python hmc_tomography test; else python3 hmc_tomography test; fi
