language: python

matrix:
  include:
    - name: "Python 3.6.5 on macOS (xcode9.4)"
      os: osx
      osx_image: xcode9.4
      language: shell
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov
    - name: "Python 3.7.3 on macOS (xcode10.2)"
      os: osx
      osx_image: xcode10.2
      language: shell
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov
    - name: "Python 3.6 on Linux"
      os: linux
      language: python
      python: 3.6
    - name: "Python 3.7 on Linux"
      os: linux
      language: python
      python: 3.7
    - name: "Python 3.6.8 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip install -e .

script:
  - which python
  - python -m hmc_tomography test
