name: hmc-tomography
dependencies:
- python=3.7
- numpy
- pyyaml
- h5py
- termcolor
- tqdm
- matplotlib
- numpydoc # everything here on onwards are development / documentation packages and not strictly required.
- sphinx_rtd_theme
